export const COURSE_CATALOG = [
  { key: "stats", diplomaIncludes: "القانون", levelEquals: "الأول" },
  { key: "eng1", diplomaIncludes: "القانون", levelEquals: "الأول" },
  { key: "law", diplomaIncludes: "القانون", levelEquals: "الأول" },
  { key: "writing", diplomaIncludes: "القانون", levelEquals: "الأول" },
  { key: "learning", diplomaIncludes: "القانون", levelEquals: "الثاني" },
  { key: "career", diplomaIncludes: "القانون", levelEquals: "الثاني" },
  { key: "admin_law", diplomaIncludes: "القانون", levelEquals: "الثاني" },
  { key: "islamic_law", diplomaIncludes: "القانون", levelEquals: "الثاني" },
  { key: "criminal_law", diplomaIncludes: "القانون", levelEquals: "الثاني" },
  { key: "eng2", diplomaIncludes: "القانون", levelEquals: "الثالث" },
  { key: "family_law", diplomaIncludes: "القانون", levelEquals: "الثالث" },
  { key: "insurance_law", diplomaIncludes: "القانون", levelEquals: "الثالث" },
  { key: "advanced_computer", diplomaIncludes: "القانون", levelEquals: "الثالث" },
  { key: "obligation", diplomaIncludes: "القانون", levelEquals: "الرابع" },
  { key: "commercial_law", diplomaIncludes: "القانون", levelEquals: "الرابع" },
  { key: "judiciary", diplomaIncludes: "القانون", levelEquals: "الرابع" },

  // المستشفيات
  { key: "math", diplomaIncludes: "المستشفيات", levelEquals: "الأول" },
  { key: "eng1", diplomaIncludes: "المستشفيات", levelEquals: "الأول" },
  { key: "business", diplomaIncludes: "المستشفيات", levelEquals: "الأول" },
  { key: "computer", diplomaIncludes: "المستشفيات", levelEquals: "الثاني" },
  { key: "career", diplomaIncludes: "المستشفيات", levelEquals: "الثاني" },
  { key: "writing", diplomaIncludes: "المستشفيات", levelEquals: "الثاني" },
  { key: "hospital", diplomaIncludes: "المستشفيات", levelEquals: "الثاني" },
  { key: "eng2", diplomaIncludes: "المستشفيات", levelEquals: "الثالث" },
  { key: "stats", diplomaIncludes: "المستشفيات", levelEquals: "الثالث" },
  { key: "islamic_studies", diplomaIncludes: "المستشفيات", levelEquals: "الثالث" },
  { key: "advanced_computer", diplomaIncludes: "المستشفيات", levelEquals: "الثالث" },
  { key: "accounting", diplomaIncludes: "المستشفيات", levelEquals: "الرابع" },
  { key: "health", diplomaIncludes: "المستشفيات", levelEquals: "الرابع" },
  { key: "health_hrm", diplomaIncludes: "المستشفيات", levelEquals: "الرابع" },

  // الموارد البشرية
  { key: "math", diplomaIncludes: "الموارد البشرية", levelEquals: "الأول" },
  { key: "eng1", diplomaIncludes: "الموارد البشرية", levelEquals: "الأول" },
  { key: "business", diplomaIncludes: "الموارد البشرية", levelEquals: "الأول" },
  { key: "career", diplomaIncludes: "الموارد البشرية", levelEquals: "الثاني" },
  { key: "writing", diplomaIncludes: "الموارد البشرية", levelEquals: "الثاني" },
  { key: "hrm_principles", diplomaIncludes: "الموارد البشرية", levelEquals: "الثاني" },
  { key: "learning", diplomaIncludes: "الموارد البشرية", levelEquals: "الثاني" },
  { key: "job_analysis", diplomaIncludes: "الموارد البشرية", levelEquals: "الثالث" },
  { key: "stats", diplomaIncludes: "الموارد البشرية", levelEquals: "الثالث" },
  { key: "islamic_studies", diplomaIncludes: "الموارد البشرية", levelEquals: "الثالث" },
  { key: "eng2", diplomaIncludes: "الموارد البشرية", levelEquals: "الثالث" },
  { key: "hr_planning", diplomaIncludes: "الموارد البشرية", levelEquals: "الرابع" },
  { key: "learning", diplomaIncludes: "الموارد البشرية", levelEquals: "الرابع" },
  { key: "accounting", diplomaIncludes: "الموارد البشرية", levelEquals: "الرابع" },

  // الادارة المكتبية
  { key: "eng1", diplomaIncludes: "الادارة المكتبية", levelEquals: "الأول" },
  { key: "math", diplomaIncludes: "الادارة المكتبية", levelEquals: "الأول" },
  { key: "business", diplomaIncludes: "الادارة المكتبية", levelEquals: "الأول" },
  { key: "eng2", diplomaIncludes: "الادارة المكتبية", levelEquals: "الثاني" },
  { key: "computer", diplomaIncludes: "الادارة المكتبية", levelEquals: "الثاني" },
  { key: "writing", diplomaIncludes: "الادارة المكتبية", levelEquals: "الثاني" },
  { key: "arabic_typing", diplomaIncludes: "الادارة المكتبية", levelEquals: "الثاني" },
  { key: "admin_comm", diplomaIncludes: "الادارة المكتبية", levelEquals: "الثالث" },
  { key: "english_typing", diplomaIncludes: "الادارة المكتبية", levelEquals: "الثالث" },
  { key: "stats", diplomaIncludes: "الادارة المكتبية", levelEquals: "الثالث" },
  { key: "writing", diplomaIncludes: "الادارة المكتبية", levelEquals: "الرابع" },
  { key: "islamic_studies", diplomaIncludes: "الادارة المكتبية", levelEquals: "الرابع" },
  { key: "advanced_computer", diplomaIncludes: "الادارة المكتبية", levelEquals: "الرابع" },
  { key: "office_tech", diplomaIncludes: "الادارة المكتبية", levelEquals: "الرابع" },

  // إدارة التمريض
  { key: "business", diplomaIncludes: "إدارة التمريض", levelEquals: "الأول" },
  { key: "computer", diplomaIncludes: "إدارة التمريض", levelEquals: "الأول" },
  { key: "eng1", diplomaIncludes: "إدارة التمريض", levelEquals: "الأول" },

  // إدارة السلامة
  { key: "computer", diplomaIncludes: "إدارة السلامة", levelEquals: "الأول" },
  { key: "eng1", diplomaIncludes: "إدارة السلامة", levelEquals: "الأول" },
  { key: "safety", diplomaIncludes: "إدارة السلامة", levelEquals: "الأول" },
  { key: "math", diplomaIncludes: "إدارة السلامة", levelEquals: "الثاني" },
  { key: "career", diplomaIncludes: "إدارة السلامة", levelEquals: "الثاني" },
  { key: "safety_law", diplomaIncludes: "إدارة السلامة", levelEquals: "الثاني" },
  { key: "safety_systems", diplomaIncludes: "إدارة السلامة", levelEquals: "الثاني" },
  { key: "advanced_computer", diplomaIncludes: "إدارة السلامة", levelEquals: "الثالث" },
  { key: "industrial_safety", diplomaIncludes: "إدارة السلامة", levelEquals: "الثالث" },
  { key: "facility_safety", diplomaIncludes: "إدارة السلامة", levelEquals: "الثالث" },
  { key: "eng2", diplomaIncludes: "إدارة السلامة", levelEquals: "الرابع" },
  { key: "stats", diplomaIncludes: "إدارة السلامة", levelEquals: "الرابع" },
  { key: "safety_reports", diplomaIncludes: "إدارة السلامة", levelEquals: "الرابع" },
  { key: "safety_management", diplomaIncludes: "إدارة السلامة", levelEquals: "الرابع" },

  // إدارة الأعمال
  { key: "computer", diplomaIncludes: "إدارة الأعمال", levelEquals: "الأول" },
  { key: "eng1", diplomaIncludes: "إدارة الأعمال", levelEquals: "الأول" },
  { key: "business", diplomaIncludes: "إدارة الأعمال", levelEquals: "الأول" },
  { key: "learning", diplomaIncludes: "إدارة الأعمال", levelEquals: "الأول" },
  { key: "math", diplomaIncludes: "إدارة الأعمال", levelEquals: "الثاني" },
  { key: "economics", diplomaIncludes: "إدارة الأعمال", levelEquals: "الثاني" },
  { key: "accounting", diplomaIncludes: "إدارة الأعمال", levelEquals: "الثاني" },
  { key: "islamic_studies", diplomaIncludes: "إدارة الأعمال", levelEquals: "الثاني" },
  { key: "business_world1", diplomaIncludes: "إدارة الأعمال", levelEquals: "الثالث" },
  { key: "eng2", diplomaIncludes: "إدارة الأعمال", levelEquals: "الثالث" },
  { key: "organizational", diplomaIncludes: "إدارة الأعمال", levelEquals: "الثالث" },
  { key: "stats", diplomaIncludes: "إدارة الأعمال", levelEquals: "الثالث" },
  { key: "marketing", diplomaIncludes: "إدارة الأعمال", levelEquals: "الرابع" },
  { key: "hrm", diplomaIncludes: "إدارة الأعمال", levelEquals: "الرابع" },
  { key: "finance", diplomaIncludes: "إدارة الأعمال", levelEquals: "الرابع" },
  { key: "business_english", diplomaIncludes: "إدارة الأعمال", levelEquals: "الخامس" },
  { key: "mis", diplomaIncludes: "إدارة الأعمال", levelEquals: "الخامس" },
  { key: "operations", diplomaIncludes: "إدارة الأعمال", levelEquals: "الخامس" },
  { key: "e_management", diplomaIncludes: "إدارة الأعمال", levelEquals: "الخامس" },
  { key: "quality", diplomaIncludes: "إدارة الأعمال", levelEquals: "السادس" },
  { key: "strategy", diplomaIncludes: "إدارة الأعمال", levelEquals: "السادس" },
  { key: "business_world2", diplomaIncludes: "إدارة الأعمال", levelEquals: "السادس" },
  { key: "resource_management", diplomaIncludes: "إدارة الأعمال", levelEquals: "السابع" },
  { key: "english_reports", diplomaIncludes: "إدارة الأعمال", levelEquals: "السابع" },
  { key: "operations", diplomaIncludes: "إدارة الأعمال", levelEquals: "السابع" },

  // الأمن السيبراني (محدّث)
  { key: "business_world1", diplomaIncludes: "الأمن السيبراني", levelEquals: "الأول" },
  { key: "computer", diplomaIncludes: "الأمن السيبراني", levelEquals: "الأول" },
  { key: "eng1", diplomaIncludes: "الأمن السيبراني", levelEquals: "الأول" },
  { key: "algorithms", diplomaIncludes: "الأمن السيبراني", levelEquals: "الأول" },
  { key: "eng2", diplomaIncludes: "الأمن السيبراني", levelEquals: "الثاني" },
  { key: "advanced_computer", diplomaIncludes: "الأمن السيبراني", levelEquals: "الثاني" },
  { key: "math", diplomaIncludes: "الأمن السيبراني", levelEquals: "الثاني" },
  { key: "business_world2", diplomaIncludes: "الأمن السيبراني", levelEquals: "الثاني" },
  { key: "networking", diplomaIncludes: "الأمن السيبراني", levelEquals: "الثالث" },
  { key: "programming", diplomaIncludes: "الأمن السيبراني", levelEquals: "الثالث" },
  { key: "cryptography", diplomaIncludes: "الأمن السيبراني", levelEquals: "الثالث" },
  { key: "python", diplomaIncludes: "الأمن السيبراني", levelEquals: "الرابع" },
  { key: "eng3", diplomaIncludes: "الأمن السيبراني", levelEquals: "الرابع" },
  { key: "programming1", diplomaIncludes: "الأمن السيبراني", levelEquals: "الرابع" },
  { key: "cybersecurity", diplomaIncludes: "الأمن السيبراني", levelEquals: "الخامس" },
  { key: "os1", diplomaIncludes: "الأمن السيبراني", levelEquals: "الخامس" },
  { key: "cyber", diplomaIncludes: "الأمن السيبراني", levelEquals: "السادس" },
  { key: "cloud", diplomaIncludes: "الأمن السيبراني", levelEquals: "السادس" },
  { key: "ai", diplomaIncludes: "الأمن السيبراني", levelEquals: "السادس" },
  { key: "os2", diplomaIncludes: "الأمن السيبراني", levelEquals: "السابع" },
  { key: "info_security", diplomaIncludes: "الأمن السيبراني", levelEquals: "السابع" },
  { key: "ethical_hacking", diplomaIncludes: "الأمن السيبراني", levelEquals: "السابع" },
];